improved CMakeLists.txt to make it more readable and now using different vars for install and build dirs

diff --git a/cgfcollector/tools/test_runner.sh.in b/cgfcollector/tools/test_runner.sh.in
--- a/cgfcollector/tools/test_runner.sh.in
+++ b/cgfcollector/tools/test_runner.sh.in
@@ -2,6 +2,11 @@
 
 test_case_dir="@FCOLLECTOR_TEST_CASES_DIR@"
 
+if ! [ -d "$test_case_dir" ]; then
+    echo "Error: Test case directory '$test_case_dir' does not exist."
+    exit 1
+fi
+
 scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
 out_dir="$scriptdir/out"
 
