Add verbosity option to cage test runner

diff --git a/tools/cage/test/runCaGeTests.sh.in b/tools/cage/test/runCaGeTests.sh.in
--- a/tools/cage/test/runCaGeTests.sh.in
+++ b/tools/cage/test/runCaGeTests.sh.in
@@ -7,6 +7,7 @@ cgdiff="$build_dir/tools/cgdiff/cgdiff"
 cgmerge="$build_dir/tools/cgmerge2/cgmerge2"
 
 suite_pattern=".*"
+verbose=0
 
 mkdir -p log
 
@@ -35,34 +36,40 @@ function runTestCase {
   o_files=()
 
   for testTU in $(ls $testCasePath | grep "$testCaseName.*\.cpp"); do
+    failed=0
     tfile_out="$run_dir/$testTU.o"
     rm -f "$tfile_out"
-    clang++ -c -g `$mcgconfig --cage --cxxflags` ${addFlags} -fno-exceptions "$testCasePath/$testTU" -o  "$tfile_out" >> log/testrun.log 2>&1
-    if [[ $? -ne 0 ]]; then
-      echo "Compilation failed!"
+    clang++ -c -g `$mcgconfig --cage --cxxflags` ${addFlags} -fno-exceptions "$testCasePath/$testTU" -o  "$tfile_out" >> log/testrun.log 2>&1 || failed=1
+    if [[ $failed -ne 0 ]] || [[ $verbose -eq 1 ]]; then
       echo "Compile command: clang++ -c -g `$mcgconfig --cage --cxxflags` ${addFlags} -fno-exceptions $testCasePath/$testTU -o $tfile_out"
+    fi
+    if [[ $failed -ne 0 ]]; then
+      echo "Compilation failed!"
       return 1
     fi
     o_files+=($tfile_out)
   done
 
+  failed=0
   tfile_out="$run_dir/$testCaseName.exe"
   rm -f "$tfile_out"
-  CAGE_CG_NAME="$cg_outfile" clang++ -g `$mcgconfig --cage --ldflags` ${addFlags} -fno-exceptions ${o_files[@]} -o  "$tfile_out" >> log/testrun.log 2>&1
-   if [[ $? -ne 0 ]]; then
-      echo "Link command: CAGE_CG_NAME=$cg_outfile clang++ -g `$mcgconfig --cage --ldflags` ${addFlags} -fno-exceptions ${o_files[@]} -o  $tfile_out"
-      if [[ ! -f "$cg_outfile" ]]; then
-        echo "Linking failed! No call graph generated."
-        return 1
-      fi
-      echo "Linking failed but call graph was generated."
-   fi
+  CAGE_CG_NAME="$cg_outfile" clang++ -g `$mcgconfig --cage --ldflags` ${addFlags} -fno-exceptions ${o_files[@]} -o  "$tfile_out" >> log/testrun.log 2>&1 || failed=1
+  if [[ $failed -ne 0 ]] || [[ $verbose -eq 1 ]]; then
+    echo "Link command: CAGE_CG_NAME=$cg_outfile clang++ -g `$mcgconfig --cage --ldflags` ${addFlags} -fno-exceptions ${o_files[@]} -o  $tfile_out"
+  fi
+  if [[ $failed -ne 0 ]]; then
+    if [[ ! -f "$cg_outfile" ]]; then
+      echo "Linking failed! No call graph generated."
+      return 1
+    fi
+    echo "Linking failed but call graph was generated."
+  fi
 
-   if [[ $regenerate_gt -eq 1 ]]; then
-     echo "Using $cg_outfile as new ground truth"
-     cp "$cg_outfile" "$cg_gtfile"
-     return 0
-   fi
+  if [[ $regenerate_gt -eq 1 ]]; then
+   echo "Using $cg_outfile as new ground truth"
+   cp "$cg_outfile" "$cg_gtfile"
+   return 0
+  fi
 
   "$cgdiff" --ignore-hasBody --ignore-md --ignore-edge-md "$cg_outfile" "$cg_gtfile" -o "$diff_file" -- >>log/testrun.log 2>&1
   fail=$?
@@ -131,11 +138,14 @@ function runMultiFileTests {
   return $fails
 }
 
-while getopts ":hrs:" opt; do
+while getopts ":hvrs:" opt; do
   case $opt in
     h)
       echo "use -h to print this help"
       exit 0
+      ;;
+    v)
+      verbose=1
       ;;
     r)
       regenerate_gt=1
