add cmake managed tests for multi file tests

diff --git a/cgfcollector/test/test_runner.sh.in b/cgfcollector/test/test_runner.sh.in
--- a/cgfcollector/test/test_runner.sh.in
+++ b/cgfcollector/test/test_runner.sh.in
@@ -7,7 +7,57 @@ if [[ ! -d "$out_dir" ]]; then
     mkdir "$out_dir"
 fi
 
-find "$test_case_dir" . -mindepth 1 -type d | while read -r dir; do
+# cmake managed test dirs
+find "$test_case_dir" -mindepth 1 -type d \! -exec test -e "{}/output.json" \; \! -exec test -e "{}/*.f90" \; -exec find {} -maxdepth 1 -name 'CMakeLists.txt' \; | while read -r dir; do
+    dir="$(dirname "$dir")"
+
+    tmp_dir="$(mktemp -d)"
+
+    copy_to="$(pwd)/$out_dir"
+    if [[ ! -d "$copy_to" ]]; then
+        echo "Error: $copy_to does not exist"
+    fi
+
+    echo "Running cmake managed tests from dir: $(basename "$dir")"
+
+    {
+        cd "$dir"
+        cmake -S . -B "$tmp_dir"
+        cd "$tmp_dir"
+        make
+        find . -maxdepth 1 -name '*.json' | while read -r file; do
+            cp "$file" "$copy_to/$(basename "$dir")_$(basename "$file")"
+
+            test_case_name="$(basename "$dir")_$(basename -s .json "$file")"
+
+            echo "Test case: $test_case_name"
+
+            output_file="$dir/$(basename -s .json "$file")/output.json"
+
+            if [[ -f "$output_file" ]] && [[ -s "$output_file" ]] && grep -q '{}' "$output_file"; then
+                echo "Skipping empty or missing output file: $output_file"
+                continue
+            fi
+
+            if @FCOLLECTOR_CG_COMPARE@ "$output_file" "$copy_to/$(basename "$dir")_$(basename "$file")"; then
+                echo "Test case passed"
+            else
+                echo "Error: Output mismatch"
+            fi
+
+        done
+    } || {
+        echo "Error: could not generate CG"
+        rm -rf "$tmp_dir"
+        continue
+    }
+
+    rm -rf "$tmp_dir"
+done
+
+# no cmake managed test dirs
+find "$test_case_dir" -mindepth 1 -type d \! -exec test -e "{}/CMakeLists.txt" \; -exec find {} -maxdepth 1 -name "output.json" \; | while read -r dir; do
+    dir="$(dirname "$dir")"
     mapfile -t input_files < <(find "$dir" -maxdepth 1 -name '*.f90')
     output_file="$dir/output.json"
 
